In [1]:
import numpy as np

# 1. Array Creation Techniques
print("1. Array Creation Techniques")

1. Array Creation Techniques


In [2]:
array_from_list = np.array([1, 2, 3, 4, 5])
array_from_list

array([1, 2, 3, 4, 5])

In [3]:
array_arange = np.arange(0, 10, 2)
array_arange

array([0, 2, 4, 6, 8])

In [4]:
array_linspace = np.linspace(0, 10, 5)  # Divides 0 to 10 into 5 points
array_linspace


array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
array_zeros = np.zeros((3, 3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_ones = np.ones((2, 2))
array_ones

array([[1., 1.],
       [1., 1.]])

In [7]:
array_eye = np.eye(3)
array_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
array_random = np.random.random((3, 3))
array_random

array([[0.8461707 , 0.49384405, 0.08912318],
       [0.69804169, 0.08747803, 0.80657178],
       [0.87941755, 0.3067335 , 0.16980128]])

In [9]:
print("\n2. NumPy Methods")

# a. Reshaping an array
reshaped_array = np.arange(1, 10).reshape(3, 3)
reshaped_array


2. NumPy Methods


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
transposed_array = reshaped_array.T
transposed_array

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
array_math = np.array([1, 2, 3])
array_math + 2
array_math * 3
np.sqrt(array_math)


array([1.        , 1.41421356, 1.73205081])

In [12]:
np.sum(array_math)
np.mean(array_math)
np.max(array_math)
np.min(array_math)

1

In [13]:
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])
concat_array = np.concatenate((array_a, array_b))
concat_array

array([1, 2, 3, 4, 5, 6])

In [14]:
unsorted_array = np.array([3, 1, 4, 2])
sorted_array = np.sort(unsorted_array)
sorted_array

# g. Indexing and Slicing
indexed_value = array_math[1]  # Indexing
indexed_value
sliced_array = array_math[1:3]  # Slicing
sliced_array

# h. Boolean Masking
boolean_mask = array_math > 2
boolean_mask
array_math[boolean_mask]

array([3])